name : Orange County DevOps Website
brand : Orange County DevOps
description : This is the website for the Orange County DevOps Meetup Group
keyword : DevOps, OC DevOps, Orange County DevOps
url : http://www.ocdevops.org
email : chris@nebulaworks.com
twitter : oc_devops
github : oc-devops
author : Chris Ciborowski
year : 2017
markdown : kramdown
exclude :
  - node_modules
